shri-2015-org/shrimp

- .gitignore
- README.md
- app/app.jsx
- app/components/index/index.jsx
- app/components/index/styles.scss
- make-webpack-config.js
- package.json
- server/server.js
- webpack-dev.config.js
- webpack-production.config.js
Merge whole lot of boilerplate code, including server boilerplate. Feel free to overwrite to this code if you wish.
Resolves: #5
> Setup initial infrastructure

- package.json
- server/server.js
- server/socket.js
Add socket.io server for transport state between frontend and backend.
Related: #10
> feat(server): add socket.io server

- package.json
In future client tests would go to `test-client` command, so we need ot
prepare for that.
Closes: #21
> fix(tests): fix tests to run correctly

- package.json
Also configure `npm test` to run linting.
> chore(project): run `npm test` in pre-commit hook

- README.md
This spec is meant to be used as a reference by all teams. If you propose changes to this spec, edit this spec first and create a PR.
> docs(project): client state spec

- app/app.jsx
- app/components/message-box/index.jsx
- app/core/core.js
- app/core/socket.js
- app/selectors/messagesSelector.js
- package.json
- server/server.js
- server/socket.js
Add sockets on client and server state. Message sends on connected users.
> feat(socket): Add sockets: send message

- .editorconfig
Add editorconfig file
Related #39
> chore(editorconfig): add editorconfig file

- package.json
This change is needed for Heroku deploy
> chore: specify node version

- README.md
In future pending messages should probably go to messages list and just be marked as pending.
> docs: remove pendingMessages

- app/actions/local.js
- app/reducers/local.js
- app/tests/reducers/local_spec.js
This reducer deals with state that is local to the client and does need
to relate to the server.
> feat: add local reducer

- app/components/ChannelItem/index.jsx
- app/components/ChannelItem/styles.scss
- app/components/PeopleItem/index.jsx
- app/components/PeopleItem/styles.scss
- app/components/Threads/index.jsx
- app/components/ThreadsList/index.jsx
- app/components/ThreadsList/styles.scss
> feat(components): pepleList and channelsList

- app/selectors/messagesSelector.js
- app/tests/selectors/messagesSelector_spec.js
> feat(selectors): fetch user object in `messagesSelector`

- app/root.html
- server/server.js
> feat: extract html from server.js to app/root.html

- app/Root.jsx
delete cookie switcher because devtools already has ctrl+h switcher
> Redux DevTools: delete cookie switcher

- package.json
closes #89 
add contributors
add node version
> feat: Clean package.json

- app/App.jsx
- app/components/Header/index.jsx
- app/components/Header/styles.scss
- app/components/Message/index.jsx
- app/components/Message/styles.scss
- app/components/MessageComposer/index.jsx
- app/components/MessageComposer/styles.scss
- app/components/MessageList/styles.scss
- app/components/Messages/index.jsx
- app/components/Messages/styles.scss
- app/components/Threads/styles.scss
- app/root.html
- app/styles/variables.scss
- package.json
> Added sidebar for mobile version

- app/App.jsx
- app/components/Threads/index.jsx
- app/selectors/contactsSelector.js
> feat: remove current user from contacts

- app/components/ChannelItem/index.jsx
- app/components/ChannelItem/styles.scss
- app/components/PeopleItem/index.jsx
- app/components/PeopleItem/styles.scss
- app/components/UnreadCounter/index.jsx
- app/components/UnreadCounter/styles.scss
• Redesign people tab
• Add UnreadCount component
Required merge #160
> Redesign people tab

- app/components/MessageComposer/index.jsx
> feat(components): fix maxlenght

- app/components/SignUp/index.jsx
- package.json
- server/db/db_core.js
- server/models/user.js
- server/server.js
The gravatar link is based on md5 hash of user e-mail address.
> feat: use Gravatars for avatars

- app/App.jsx
- app/components/Login/index.jsx
- app/components/SignUp/index.jsx
- app/root.html
- package.json
> feat(components): added title for pages

- app/components/NewChannelItem/index.jsx
- app/components/Search/index.jsx
- app/components/Threads/index.jsx
> fix bug with hidding channel when filter is active

- app/components/SignUp/index.jsx
Fix validation for email. Close #257
> fix(validation): fix validation for email

- app/components/Dropdown/styles.scss
- app/components/Header/styles.scss
- make-webpack-config.js
- package.json
I used this guide:
http://mts.io/2015/04/08/webpack-shims-polyfills/
https://gist.github.com/Couto/b29676dd1ab8714a818f
> Added fetch polyfill

- app/App.jsx
- server/db/db_core.js
- server/models/channel.js
Поправил костыль, когда при первом заходе в чат после регистрации, пользователь не мог отправлять сообщения не кликнув по каналу.
> Fix bug for first signin user

- app/components/Threads/index.jsx
- app/reducers/channels.js
> added sort channels by favorite

- app/components/Settings/index.jsx
> fix(settings): add email validation

- make-webpack-config.js
- package.json
> Fix fetch polyfill

- app/components/Button/index.jsx
- app/components/Button/styles.scss
- app/components/Login/index.jsx
- app/components/Messages/index.jsx
- app/components/Settings/index.jsx
- app/components/SignUp/index.jsx
- app/components/Threads/index.jsx
- app/components/ThreadsList/index.jsx
Rewrite passing props with `{...this.props}`
Add gray state after pressing button (like GitHub)
> gray buttons and refactor

- app/components/LoginWindow/index.jsx
- app/components/LoginWindow/styles.scss
- app/components/PopUp/index.jsx
- app/components/PopUp/styles.scss
- app/components/Settings/index.jsx
No visual changes.
Only separate popup animation to individual component.
> add component popup

- app/core/socket.js
Fix redirecting to login page if invalid sessionId
> fix(core): fix redirecting to login page if invalid sessionId
